#!/usr/bin/env bash
set -e

## Description: Sets env for all job steps from GitHub event, as well as some predefined values to be used for any job. This step should always be included in any action.

gitRepo() {
	git remote -v 2>/dev/null |
		head -n1 |
		awk '{print $2}' |
		sed -e 's,.*:\(.*/\)\?,,' -e 's/\.git$//'
}

getrunnerenv() {
	aws secretsmanager \
		get-secret-value \
		--secret-id actions/runner-env \
		--query SecretString \
		--output text \
		--region us-east-1 |
		jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]'
}
# shellcheck disable=SC2046
export $(getrunnerenv)

echo "Job env:"
echo "――――――――――――――――――――――"
echo "HOME="$HOME
echo "GITHUB_WORKFLOW="$GITHUB_WORKFLOW
echo "GITHUB_RUN_ID="$GITHUB_RUN_ID
echo "GITHUB_RUN_NUMBER="$GITHUB_RUN_NUMBER
echo "GITHUB_ACTION="$GITHUB_ACTION
echo "GITHUB_ACTIONS="$GITHUB_ACTIONS
echo "GITHUB_ACTOR="$GITHUB_ACTOR
echo "GITHUB_REPOSITORY="$GITHUB_REPOSITORY
echo "GITHUB_EVENT_NAME="$GITHUB_EVENT_NAME
echo "GITHUB_EVENT_PATH="$GITHUB_EVENT_PATH
echo "GITHUB_WORKSPACE="$GITHUB_WORKSPACE
echo "GITHUB_SHA="$GITHUB_SHA
echo "GITHUB_REF="$GITHUB_REF
echo "GITHUB_HEAD_REF="$GITHUB_HEAD_REF
echo "GITHUB_BASE_REF="$GITHUB_BASE_REF
echo "――――――――――――――――――――――"

echo "Setting env for steps:"
echo "――――――――――――――――――――――"

echo "GPR_TOKEN=$GPR_TOKEN" >>$GITHUB_ENV
echo "Set GPR_TOKEN=******"

echo "NPM_AUTH_TOKEN=$GPR_TOKEN" >>$GITHUB_ENV
echo "Set NPM_AUTH_TOKEN=******"

echo "NODE_AUTH_TOKEN=$GPR_TOKEN" >>$GITHUB_ENV
echo "Set NODE_AUTH_TOKEN=******"

echo "NPM_TOKEN=$GPR_TOKEN" >>$GITHUB_ENV
echo "Set NPM_TOKEN=******"

export REPO=$(gitRepo)
echo "REPO=$REPO" >>$GITHUB_ENV
echo "Set REPO=$REPO"

export LANGUAGE=$(curl -s -X GET https://$GPR_TOKEN:@api.github.com/repos/$GITHUB_REPOSITORY | jq -r '.language')
echo "LANGUAGE=$LANGUAGE" >>$GITHUB_ENV
echo "Set LANGUAGE=$LANGUAGE"

export BRANCH=${GITHUB_REF#refs/heads/}
echo "BRANCH=$BRANCH" >>$GITHUB_ENV
echo "Set BRANCH=$BRANCH"
echo "TARGET_ENV=$TARGET_ENV" >>$GITHUB_ENV
echo "Set TARGET_ENV=$TARGET_ENV"
echo "NODE_ENV=$NODE_ENV" >>$GITHUB_ENV
echo "Set NODE_ENV=$NODE_ENV"

export RFC_REPO=$(echo $REPO | sed 's/\./-/g; s/_/-/g')
echo "RFC_REPO=$RFC_REPO" >>$GITHUB_ENV
echo "Set RFC_REPO=$RFC_REPO"

export GIT_SHORT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
echo "GIT_SHORT_HASH=$GIT_SHORT_HASH" >>$GITHUB_ENV
echo "Set GIT_SHORT_HASH=$GIT_SHORT_HASH"

export REVISION=${GITHUB_REF##*/}
echo "REVISION=$REVISION" >>$GITHUB_ENV
echo "Set REVISION=$REVISION"

export DOCKER_BUILDKIT=1
echo "DOCKER_BUILDKIT=$DOCKER_BUILDKIT" >>$GITHUB_ENV
echo "Set DOCKER_BUILDKIT=$DOCKER_BUILDKIT"

echo "――――――――――――――――――――――"
echo "Complete"
