#!/bin/bash
set -e


GITUSER=$(git config -l | grep user.name | cut -d "=" -f2)

gitRepo() {
	git remote -v 2>/dev/null | \
		head -n1 | \
		awk '{print $2}' | \
		sed -e 's,.*:\(.*/\)\?,,' -e 's/\.git$//'
}

# shellcheck disable=SC2046
export $(getrunnerenv)

echo "Job env:"
echo "――――――――――――――――――――――"
echo "HOME="$HOME
echo "GITHUB_WORKFLOW="$GITHUB_WORKFLOW
echo "GITHUB_RUN_ID="$GITHUB_RUN_ID
echo "GITHUB_RUN_NUMBER="$GITHUB_RUN_NUMBER
echo "GITHUB_ACTION="$GITHUB_ACTION
echo "GITHUB_ACTIONS="$GITHUB_ACTIONS
echo "GITHUB_ACTOR="$GITHUB_ACTOR
echo "GITHUB_REPOSITORY="$GITHUB_REPOSITORY
echo "GITHUB_EVENT_NAME="$GITHUB_EVENT_NAME
echo "GITHUB_EVENT_PATH="$GITHUB_EVENT_PATH
echo "GITHUB_WORKSPACE="$GITHUB_WORKSPACE
echo "GITHUB_SHA="$GITHUB_SHA
echo "GITHUB_REF="$GITHUB_REF
echo "GITHUB_HEAD_REF="$GITHUB_HEAD_REF
echo "GITHUB_BASE_REF="$GITHUB_BASE_REF
echo "――――――――――――――――――――――"

echo "Setting env for steps:"
echo "――――――――――――――――――――――"

echo "::set-env name=GPR_TOKEN::$GPR_TOKEN"
	echo "Set GPR_TOKEN=******"

export REPO=$(gitRepo)
	echo "::set-env name=REPO::$REPO"
	echo "Set REPO=$REPO"

export LANGUAGE=$(curl -s -X GET https://$GPR_TOKEN:@api.github.com/repos/$GITHUB_REPOSITORY | jq -r '.language')
	echo "::set-env name=LANGUAGE::$LANGUAGE"
	echo "Set LANGUAGE=$LANGUAGE"

export BRANCH=${GITHUB_REF#refs/heads/}

export RFC_REPO=$(echo $REPO | sed 's/\./-/g; s/_/-/g')
	echo "::set-env name=RFC_REPO::$RFC_REPO"
	echo "Set RFC_REPO=$RFC_REPO"

export GIT_SHORT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
	echo "::set-env name=GIT_SHORT_HASH::$GIT_SHORT_HASH"

export GPR_PROJECT=docker.pkg.github.com/$GITUSER/$REPO
	echo "::set-env name=GPR_PROJECT::$GPR_PROJECT"
	echo "Set GPR_PROJECT=$GPR_PROJECT"

export REVISION=${GITHUB_REF##*/}
	echo "::set-env name=REVISION::$REVISION"
	echo "Set REVISION=$REVISION"

export ECR_PREFIX="$ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/$RFC_REPO"
	echo "::set-env name=ECR_PREFIX::$ECR_PREFIX"
	echo "Set ECR_PREFIX=$ECR_PREFIX"

export ECR_TAG="$ECR_PREFIX:$GIT_SHORT_HASH"
	echo "::set-env name=ECR_TAG::$ECR_TAG"
	echo "Set ECR_TAG=$ECR_TAG"

export DHREPO_NAME=$GITUSER/$REPO
	echo "::set-env name=DHREPO_NAME::$DHREPO_NAME"
	echo "Set DHREPO_NAME=$DHREPO_NAME"

export DHIMAGE_TAG="$DHREPO_NAME:$GIT_SHORT_HASH"
	echo "::set-env name=DHIMAGE_TAG::$DHIMAGE_TAG"
	echo "Set DHIMAGE_TAG=$DHIMAGE_TAG"

export DHIMAGE_TAG_VERSION="$DHREPO_NAME:$(echo $GITHUB_REF | cut -d / -f 3)"
	echo "::set-env name=DHIMAGE_TAG_VERSION::$DHIMAGE_TAG_VERSION"
	echo "Set DHIMAGE_TAG_VERSION=$DHIMAGE_TAG_VERSION"

export DOCKER_BUILDKIT=1
	echo "::set-env name=DOCKER_BUILDKIT::$DOCKER_BUILDKIT"
	echo "Set DOCKER_BUILDKIT=$DOCKER_BUILDKIT"

echo "――――――――――――――――――――――"
echo "Complete"
