#!/bin/bash
set -ex

## Description: Automatically updates README.md

PROJECT_ROOT=$(git rev-parse --show-toplevel)
WAREHOUSE="$PROJECT_ROOT"/bin
AISLES=$(find "$WAREHOUSE" -type d | grep -v 'bin$')
#SUPPLY=$(find "$SUPPLY_BIN" -type f)
README_TOP=$(cat <<- EOF
## Usage

#### Adding Supplies

Add a script to the \`bin\` directory

#### Auto-updating README.md

The Supplies Index of this \`README.md\` file updates automatically when an Actions Script is added, or modified. In order for the description of an item to be displayed, the file must contain the following string on a single line anywhere within the file:

\`## Description: <Your description here on a single line>\`

# Supply Index

- 📂 __bin__
EOF
)

README_BOTTOM=$(cat <<- EOF


## Author

👤 **William Allen**

* Github: [@wallentx](https://github.com/wallentx)

EOF
)

#function walkAisles() {
#  cd "$WHAREHOUSE"/bin
#  find . -type d
#}

echo "$README_TOP" > "$PROJECT_ROOT"/README.md

#for AISLE in "$AISLES"; do
while read -r AISLE; do
  echo -e "   - 📂 __${AISLE}__" >> "$PROJECT_ROOT"/README.md
  while read -r SUPPLY_BIN; do
	  for CRATE in $SUPPLY_BIN; do
		  GHFILENAME=$(basename "$CRATE")
      AISLE_NUM=$(basename "$AISLE")
		  DESCRIPTION=$(sed -n 's/^## Description: //p' "$CRATE")
		  echo -e "      - 📄 [${GHFILENAME//-/\\-}](bin/$AISLE_NUM/$GHFILENAME)" >> "$PROJECT_ROOT"/README.md
		  if [[ -n "$DESCRIPTION" ]]; then
  			echo -e "         - _${DESCRIPTION}_" >> "$PROJECT_ROOT"/README.md
		  fi
	  done
  done < <(find "$AISLE" -type f)
done < <(echo "$AISLES")
#done < <(find "$SUPPLY_BIN" -type f)

echo "$README_BOTTOM" >> "$PROJECT_ROOT"/README.md

#cd $OLDPWD
