#!/bin/bash
set -e

## Description: Automatically updates README.md

PROJECT_ROOT=$(git rev-parse --show-toplevel)
SUPPLY_BIN=$PROJECT_ROOT/bin


## Usage

#### Adding Supplies

Add a script to the \`bin\` directory

#### Auto-updating README.md

The Supplies Index of this \`README.md\` file updates automatically when an Actions Script is added, or modified. In order for the description of an item to be displayed, the file must contain the following string on a single line anywhere within the file:

\`## Description: <Your description here on a single line>\`

# Supply Index

- 📂 __bin__
EOF
)

README_BOTTOM=$(cat <<- EOF


## Author

👤 **William Allen**

* Github: [@wallentx](https://github.com/wallentx)

EOF
)

echo "$README_TOP" > README.md


for SUPPLY in "$UPPLY_BIN"/*; do
	GHFILENAME=$(basename "$ACTION")
	DESCRIPTION=$(sed -n 's/^## Description: //p' "$SUPPLY")
	echo -e "   - 📄 [${GHFILENAME//-/\\-}](/bin/$GHFILENAME)" >> README.md
	if [[ -n "$DESCRIPTION" ]]; then
		echo -e "      - _${DESCRIPTION}_" >> README.md
	fi
done

echo "$README_BOTTOM" >> README.md

